export type Platform = {
  id: string;
  name: string;
  url: string;
  category: "full-business" | "tool-license" | "lifetime-deal" | "community";
  subcategory: "large" | "medium" | "small" | "niche" | "code" | "digital" | "research";
  priceRange: {
    min: number;
    max: number;
    currency: string;
  };
  features: string[];
  pros: string[];
  cons: string[];
  fee: string;
  dealVolume?: string;
  userBase?: string;
  specialties: string[];
  founded?: number;
  rating?: number;
};

export const platforms: Platform[] = [
  // Large Full Business
  {
    id: "acquire",
    name: "Acquire.com",
    url: "https://acquire.com",
    category: "full-business",
    subcategory: "large",
    priceRange: { min: 50000, max: 5000000, currency: "USD" },
    features: [
      "売り手手数料無料",
      "90日平均成約",
      "LOI/APA自動生成",
      "Escrow.com統合",
      "ライブメトリクス表示",
      "買収資金調達サポート",
    ],
    pros: [
      "最も洗練されたUI/UX",
      "50万人のバイヤーネットワーク",
      "手数料無料（売り手）",
      "B2B SaaSに強い",
    ],
    cons: ["最低取引額が高め（$50k〜）", "小規模案件は不向き"],
    fee: "無料（売り手）",
    userBase: "50万人以上",
    specialties: ["SaaS", "Eコマース", "モバイルアプリ", "暗号資産"],
    rating: 4.7,
  },
  {
    id: "flippa",
    name: "Flippa",
    url: "https://flippa.com",
    category: "full-business",
    subcategory: "large",
    priceRange: { min: 1000, max: 10000000, currency: "USD" },
    features: [
      "世界最大マーケットプレイス",
      "即時ベンチマーキング",
      "データ直接接続",
      "デューデリジェンスオプション",
      "法務サービス統合",
      "ファイナンシング統合",
    ],
    pros: [
      "年間12,000件の取引実績",
      "60万人のバイヤー",
      "幅広い価格帯",
      "データ分析ツール充実",
    ],
    cons: ["手数料が変動制", "品質にばらつき"],
    fee: "変動制",
    dealVolume: "12,000件/年",
    userBase: "60万人以上",
    specialties: ["全種類対応"],
    rating: 4.3,
  },
  {
    id: "empire-flippers",
    name: "Empire Flippers",
    url: "https://empireflippers.com",
    category: "full-business",
    subcategory: "large",
    priceRange: { min: 100000, max: 50000000, currency: "USD" },
    features: [
      "キュレーション型（厳格な審査）",
      "完全移行代行サービス",
      "毎週月曜新規案件公開",
      "完全データ開示",
      "移行サポート充実",
    ],
    pros: [
      "$570M+の取引実績",
      "高品質案件のみ掲載",
      "移行も完全サポート",
      "Inc. 5000認定",
    ],
    cons: ["審査が厳しい", "手数料非公開"],
    fee: "非公開",
    dealVolume: "$570M+（累計）",
    specialties: ["Eコマース", "コンテンツサイト", "Amazon FBA"],
    rating: 4.8,
  },
  {
    id: "fe-international",
    name: "FE International",
    url: "https://feinternational.com",
    category: "full-business",
    subcategory: "large",
    priceRange: { min: 500000, max: 100000000, currency: "USD" },
    features: [
      "戦略的M&Aアドバイザリー",
      "無料バリュエーション",
      "業界別レポート発行",
      "1.5億人の買い手ネットワーク",
      "チェックアウト最適化",
    ],
    pros: [
      "$50B+の取引実績",
      "1,500件以上の実績",
      "大型案件に特化",
      "専門アドバイザー",
    ],
    cons: ["最低取引額が高額（$500k〜）", "中小規模は不向き"],
    fee: "非公開",
    dealVolume: "$50B+（累計）",
    founded: 2010,
    specialties: ["テクノロジー企業", "SaaS", "Eコマース"],
    rating: 4.9,
  },
  {
    id: "website-properties",
    name: "Website Properties",
    url: "https://websiteproperties.com",
    category: "full-business",
    subcategory: "medium",
    priceRange: { min: 100000, max: 100000000, currency: "USD" },
    features: [
      "20年以上の実績",
      "詳細なビジネスバリュエーション",
      "3万人のプライベートバイヤーリスト",
      "エンドツーエンドサービス",
      "リファラルプログラム",
    ],
    pros: [
      "長い実績（20年+）",
      "カスタマイズ対応",
      "業界特化可能",
      "Axial Top 25認定",
    ],
    cons: ["手数料6%〜", "大規模案件向け"],
    fee: "6%〜（$5M以上）",
    userBase: "30,000人（バイヤーリスト）",
    founded: 2004,
    specialties: ["Webサイト", "Eコマース", "Amazon FBA", "SaaS"],
    rating: 4.6,
  },

  // Small Full Business
  {
    id: "microns",
    name: "Microns.io",
    url: "https://microns.io",
    category: "full-business",
    subcategory: "small",
    priceRange: { min: 3600, max: 250000, currency: "USD" },
    features: [
      "検証済みメトリクス完全公開",
      "年間/月間収益の詳細表示",
      "最近売却された案件も公開",
      "透明性の高い取引",
      "小規模案件特化",
    ],
    pros: [
      "小規模案件に最適（$3k〜$250k）",
      "透明性が非常に高い",
      "個人開発者向け",
      "10,000人以上登録",
    ],
    cons: ["大規模案件は扱わない", "比較的新しいプラットフォーム"],
    fee: "非公開",
    userBase: "10,000人以上",
    specialties: ["Micro-SaaS", "モバイルアプリ", "ブラウザ拡張"],
    rating: 4.5,
  },
  {
    id: "sideprojectors",
    name: "SideProjectors",
    url: "https://sideprojectors.com",
    category: "full-business",
    subcategory: "small",
    priceRange: { min: 1000, max: 100000, currency: "USD" },
    features: [
      "サイドプロジェクト特化",
      "カジュアルな雰囲気",
      "小規模案件中心",
      "初心者に優しい",
    ],
    pros: ["初心者向け", "カジュアル", "小規模案件OK"],
    cons: ["規模が小さすぎる案件も", "品質にばらつき"],
    fee: "非公開",
    specialties: ["サイドプロジェクト", "小規模スタートアップ"],
    rating: 4.0,
  },
  {
    id: "motioninvest",
    name: "MotionInvest",
    url: "https://motioninvest.com",
    category: "full-business",
    subcategory: "niche",
    priceRange: { min: 10000, max: 1000000, currency: "USD" },
    features: [
      "コンテンツ収益ビジネス特化",
      "YouTubeチャンネル売買",
      "ニッチ市場専門",
    ],
    pros: ["コンテンツビジネスに特化", "YouTubeチャンネル対応"],
    cons: ["ニッチ過ぎる", "情報が少ない"],
    fee: "非公開",
    specialties: ["コンテンツサイト", "YouTubeチャンネル"],
    rating: 3.8,
  },
  {
    id: "shopify-exchange",
    name: "Shopify Exchange",
    url: "https://exchange.shopify.com",
    category: "full-business",
    subcategory: "niche",
    priceRange: { min: 5000, max: 5000000, currency: "USD" },
    features: [
      "Shopify公式マーケットプレイス",
      "データ直接連携",
      "Shopify特化の評価指標",
      "完全統合",
    ],
    pros: [
      "Shopify公式",
      "データ完全統合",
      "Shopifyストア専用",
    ],
    cons: ["Shopifyストア限定", "他プラットフォーム不可"],
    fee: "非公開",
    specialties: ["Shopifyストア"],
    rating: 4.4,
  },

  // Tool License
  {
    id: "codecanyon",
    name: "CodeCanyon",
    url: "https://codecanyon.net",
    category: "tool-license",
    subcategory: "code",
    priceRange: { min: 10, max: 500, currency: "USD" },
    features: [
      "世界最大のコードマーケットプレイス",
      "ライセンス販売モデル",
      "クリアなドキュメント",
      "品質レビュー済み",
      "週次厳選コード紹介",
    ],
    pros: [
      "世界最大規模",
      "継続収入可能",
      "技術者コミュニティ",
      "品質保証",
    ],
    cons: ["手数料が高め", "競争激しい"],
    fee: "変動制（30-50%）",
    specialties: ["WordPress", "PHP", "モバイルアプリ", "JavaScript"],
    rating: 4.5,
  },
  {
    id: "gumroad",
    name: "Gumroad",
    url: "https://gumroad.com",
    category: "tool-license",
    subcategory: "digital",
    priceRange: { min: 10, max: 10000, currency: "USD" },
    features: [
      "個人クリエイター特化",
      "ストアフロント自動生成",
      "サブスクリプション対応",
      "0→$1の哲学",
      "シンプルすぎる設計",
    ],
    pros: [
      "副業に最適",
      "10%手数料のみ",
      "週$2.1M取引実績",
      "初心者に優しい",
    ],
    cons: ["機能がシンプル", "マーケティング機能弱い"],
    fee: "10%",
    dealVolume: "$2.1M/週（全体）",
    specialties: ["デジタル製品全般", "コース", "電子書籍"],
    rating: 4.6,
  },

  // Lifetime Deal
  {
    id: "appsumo",
    name: "AppSumo",
    url: "https://appsumo.com",
    category: "lifetime-deal",
    subcategory: "digital",
    priceRange: { min: 50, max: 500, currency: "USD" },
    features: [
      "Lifetime Deal特化",
      "60日間返金保証",
      "200万人の顧客基盤",
      "爆発的初期獲得",
      "買い切りSaaS",
    ],
    pros: [
      "200万人の顧客",
      "初期ユーザー獲得に最適",
      "即座にキャッシュフロー",
      "ブランド力",
    ],
    cons: [
      "長期収益は限定的",
      "審査が厳しい",
      "価格設定の自由度低い",
    ],
    fee: "非公開（70-80%が一般的）",
    userBase: "200万人以上",
    specialties: ["SaaSツール", "ソフトウェア"],
    rating: 4.7,
  },
  {
    id: "dealmirror",
    name: "DealMirror",
    url: "https://dealmirror.com",
    category: "lifetime-deal",
    subcategory: "digital",
    priceRange: { min: 50, max: 500, currency: "USD" },
    features: [
      "Lifetime Deal",
      "AI特化セール実施",
      "Prime会員60日返金",
      "リセラーホスティング",
    ],
    pros: ["AI特化", "AppSumo競合", "柔軟性"],
    cons: ["AppSumoより小規模", "知名度低い"],
    fee: "非公開",
    specialties: ["AIツール", "ソフトウェア"],
    rating: 4.2,
  },

  // Community / Research
  {
    id: "indie-hackers",
    name: "Indie Hackers",
    url: "https://indiehackers.com",
    category: "community",
    subcategory: "research",
    priceRange: { min: 0, max: 0, currency: "USD" },
    features: [
      "コミュニティベース",
      "Build in Publicカルチャー",
      "成功事例共有",
      "パートナー募集",
      "ストーリーテリング重視",
    ],
    pros: [
      "無料",
      "コミュニティ活発",
      "学習リソース豊富",
      "7桁ARR事例多数",
    ],
    cons: ["売買機能なし", "直接的な取引不可"],
    fee: "無料",
    specialties: ["インディー系プロジェクト"],
    rating: 4.8,
  },
  {
    id: "nugget",
    name: "Nugget.one",
    url: "https://nugget.one",
    category: "community",
    subcategory: "research",
    priceRange: { min: 0, max: 0, currency: "USD" },
    features: [
      "4,052個のスタートアップアイデア",
      "実際のユーザー需要",
      "問題→ソリューションマッチング",
      "マーケットリサーチ最適",
    ],
    pros: [
      "アイデア検証に最適",
      "ニッチ発見",
      "実需要ベース",
    ],
    cons: ["売買機能なし", "アイデアDBのみ"],
    fee: "無料/プレミアム",
    specialties: ["アイデア検証", "マーケットリサーチ"],
    rating: 4.3,
  },
  {
    id: "microsaas-dev",
    name: "MicroSaaS.dev",
    url: "https://microsaas.dev",
    category: "community",
    subcategory: "research",
    priceRange: { min: 0, max: 0, currency: "USD" },
    features: [
      "MicroSaaS構築ガイド",
      "バイウィークリーローンチ事例",
      "実例から学ぶ",
      "学習リソース",
    ],
    pros: ["MicroSaaS特化", "実践的", "無料"],
    cons: ["売買機能なし", "学習リソースのみ"],
    fee: "無料",
    specialties: ["MicroSaaS構築"],
    rating: 4.1,
  },
];

export const categories = [
  { value: "all", label: "全カテゴリ" },
  { value: "full-business", label: "ビジネス丸ごと売買" },
  { value: "tool-license", label: "ツール・ライセンス販売" },
  { value: "lifetime-deal", label: "Lifetime Deal" },
  { value: "community", label: "コミュニティ・リサーチ" },
];

export const subcategories = [
  { value: "all", label: "全規模" },
  { value: "large", label: "大規模（$100k+）" },
  { value: "medium", label: "中規模（$50k-$100k）" },
  { value: "small", label: "小規模（$1k-$50k）" },
  { value: "niche", label: "ニッチ特化" },
  { value: "code", label: "コード販売" },
  { value: "digital", label: "デジタル製品" },
  { value: "research", label: "リサーチ" },
];

export const specialtyFilters = [
  "SaaS",
  "Eコマース",
  "モバイルアプリ",
  "コンテンツサイト",
  "Amazon FBA",
  "Shopifyストア",
  "Micro-SaaS",
  "AIツール",
  "暗号資産",
  "YouTubeチャンネル",
  "コード/プラグイン",
  "デジタル製品全般",
];
